### ISSUE TITLE
Can't load paint/pa under Rails Console

### ISSUE THREAD

**Issue by mattmartini** [janlelis/paint#20]
In my `.irbrc` file I have:
`require 'paint/pa'`

Using Ruby 2.3.1 and Rails 4.2.10  (as well as previous versions of both)

   `irb` and `rails console` both load paint/pa and functions using Paint work properly.

Using Ruby 2.5.1 and Rails 5.2.1
 
   `irb` loads paint/pa and functions correctly

   `rails console` throws this error message:

   `cannot load such file -- paint/pa`

It seems that this is a Rails issue, maybe having to modifications of the irb load path.

Any insights on the issue and how to resolve?

All running under MacOS.

**Comment by janlelis** [comment]
Hi there, thanks for the feedback/issue.

Can you double check if you have added *paint* (or a gem that has a *paint* dependency like *irbtools*) to your `Gemfile`?

If this does not fix your problem, can you please post the complete stack trace of the error message

**Comment by mattmartini** [comment]
It turned out to be an rvm configuration issue.
