### ISSUE TITLE
Paint % [...] fails with frozen template

### ISSUE THREAD

**Issue by ixti** [janlelis/paint#31]
With `frozen_string_literal: true` pragma, templating fails.

``` ruby
Paint % ["%{f}(%{x})", :blue, f: "f", x: ["x", :gray]]
```

fails with:

```
paint-2.2.1/lib/paint.rb:28:in `gsub!': can't modify frozen String: "%{f}(%{x})" (FrozenError)
```

# Steps to reproduce:

``` bash
ruby --enable=frozen-string-literal \
  -r paint \
  -e 'puts(Paint % ["%{f}(%{x})", :blue, f: "f", x: ["x", :gray]])'
```

# Expected behaviour:

Work normally, as in:

``` bash
ruby -r paint \
  -e 'puts(Paint % ["%{f}(%{x})", :blue, f: "f", x: ["x", :gray]])'
```

---

![image](https://user-images.githubusercontent.com/94782/148997204-e51acd13-6889-4395-92f3-969b6eaa1de7.png)

---

# Workaround

Unfreeze template:

``` ruby
Paint % [+"%{f}(%{x})", ...]
```

---

![image](https://user-images.githubusercontent.com/94782/148997434-1b9783c7-f140-4215-b18c-afe070ce7e4c.png)

**Comment by janlelis** [comment]
Fixed in v2.3.0. Thanks for bringing this up.
